 name: occupancy_networks
 channels:
     - pytorch
 dependencies:
     - python=3.6
     # downgrade pytorch/ cuda driver to work on prince cluster
     - cudatoolkit=10.1
     - pytorch==1.6.0
     - torchvision==0.7.0
     - numpy
     - scikit-learn
     - h5py
     - scipy